/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cansiny_eform_SerialPort */

#ifndef _Included_com_cansiny_eform_SerialPort
#define _Included_com_cansiny_eform_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cansiny_eform_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_cansiny_eform_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_cansiny_eform_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cansiny_eform_SerialPort_close
  (JNIEnv *, jobject);

/*
 * Class:     com_cansiny_eform_SerialPort
 * Method:    getErrbuf
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cansiny_eform_SerialPort_getErrbuf
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_cansiny_eform_SerialPort_SerialPortFinder */

#ifndef _Included_com_cansiny_eform_SerialPort_SerialPortFinder
#define _Included_com_cansiny_eform_SerialPort_SerialPortFinder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_cansiny_eform_SerialPort_SerialPortFinder_Driver */

#ifndef _Included_com_cansiny_eform_SerialPort_SerialPortFinder_Driver
#define _Included_com_cansiny_eform_SerialPort_SerialPortFinder_Driver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
